name: 03 - DAST OWASP ZAP Scan

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "The name of the docker image to scan"
        required: true

  workflow_call:
    inputs:
      image-tag:
        type: string
        description: "The name of the docker image to scan"
        required: true
env:
  # used for docker
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ inputs.image-tag || github.event.inputs.image-tag }}

jobs:
  dast-scan:
    name: DAST Scan
    runs-on: self-hosted
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker network create nodegoat_network

      - run: docker rm mongo | true && docker run -d --name mongo -p 27017:27017 -u mongodb --network nodegoat_network --name mongo mongo:4.4

      - run: docker rm nodegoat | true && docker run -d --network nodegoat_network --name nodegoat -p 4000:4000 -e NODE_ENV -e MONGODB_URI=mongodb://mongo:27017/nodegoat ${{ env.IMAGE_TAG }} sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"

      - name: wait for container to start
        run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:4000)" != "302" ]]; do sleep 5; done' || false

      - name: test container
        run: curl -s localhost:4000/

      - name: Run ZAP OWASP full scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: "owasp/zap2docker-stable"
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://localhost:4000"
          cmd_options: '-a -r report_html.html -w report_md.md -J report_json.json -j -l WARN -z "-addoninstallall" '
          allow_issue_writing: true

      # - name: Run ZAP OWASP Baseline scan
      #   uses: zaproxy/action-baseline@v0.7.0
      #   with:
      #     docker_name: "owasp/zap2docker-stable"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     target: "http://localhost:4000"
      #     cmd_options: "-a -r report_html.html -w report_md.md -J report_json.json"

      - name: Upload html report
        uses: actions/upload-artifact@v3
        with:
          name: DAST_Report.html
          path: report_html.html

      - name: stop docker
        if: always()
        run: >-
          docker stop nodegoat &&
          docker stop mongo &&
          docker rm nodegoat &&
          docker rm mongo &&
          docker network remove nodegoat_network &&
          docker container prune --force &&
          docker image prune --force
