name: 02 - Build Docker Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag nodegoat-capstone:$(date +%s)
