name: 40 SAST

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SAST-CodeQL:
    name: Build and SAST CodeQL
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

  semgrep:
    name: SAST Semgrep
    runs-on: self-hosted

    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Perform Semgrep Analysis
        run: semgrep ci -v -o results.sarif --sarif || true
        env:
          SEMGREP_RULES: p/default p/security-audit p/r2c-security-audit p/cwe-top-25 p/owasp-top-ten

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: semgrep.sarif
          path: ${{github.workspace}}/results.sarif

      - name: Upload analysis results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v2.1.28
        with:
          sarif_file: ${{github.workspace}}/results.sarif
